### PR TITLE
1.4

### PR DESCRIPTION
**Pull request by DaisukeDaisuke**
## Have you tested?
- [x] I have tested.
- [ ] I haven't tested.

### CODE REVIEW

**Comment by poustmal** [comment]
screenshot_2018-05-26-10-11-09-621_net fengberd minecraftpe_server

**Comment by poustmal** [comment]
@DaisukeDaisuke

**Comment by DaisukeDaisuke** [comment]
screenshot_20180526-171233

**Comment by DaisukeDaisuke** [comment]
`I am using Google Translate.`

It works fine on my Android.

Please note that bluelight does not support 32-bit systems / PHP.

**Comment by XxKurumi-TokisakixX** [comment]
Thx guys

**Comment by XxKurumi-TokisakixX** [comment]
@DaisukeDaisuke if you want to join the team I send you a invite

**Comment by XxKurumi-TokisakixX** [comment]
Am currently waiting on my PC so I can't code right now

**Comment by DaisukeDaisuke** [comment]
@XxKurumi-TokisakixX  
Thank you!!

**Pull request merged**
